#include<stdio.h>
#include<signal.h>

void handle_sigint(int sig)
{
    printf("Caught signal %d\n", sig);
}

int main()
{
    signal(SIGINT, handle_sigint);
    while (1){
        printf("Hello......\n");
        sleep(1);
    }
    return 0;
}
/*
Hello......
Hello......
Hello......
Hello......
Hello......
Hello......
^CCaught signal 2
Hello......
Hello......
^CCaught signal 2
Hello......
Hello......
^CCaught signal 2
Hello......
Hello......
Hello......
Hello......
^\./script_sig.sh: line 5: 28023 Quit                    (core dumped) ./01

Displaying Hello Infinitely.
Ctrl+C : causes "Caught Signal 2" as it has been handled.
Finally Terminated by Ctrl+\
*/
