#include<stdio.h>
#include<signal.h>

void handle_sigint_quit(int sig) {
    printf("Caught signal %d\n", sig);
}
int main() {
    signal(SIGINT, handle_sigint_quit);
    signal(SIGQUIT, handle_sigint_quit);

    while (1){
        printf("Hello......\n");
        sleep(1);
    }
    return 0;
}
/*
Hello......
Hello......
^CCaught signal 2
Hello......
Hello......
^CCaught signal 2
Hello......
Hello......
^\Caught signal 3
Hello......
Hello......
^\Caught signal 3
Hello......
Hello......
^CCaught signal 2
Hello......
Hello......
^\Caught signal 3
Hello......
Hello......
^Z
[2]+  Stopped                 ./script_sig.sh


Finally Terminated by Ctrl+z
*/
